### ISSUE TITLE
Generate Data Problem 

### ISSUE THREAD

**Issue by cold-young** [vdutor/neural-diffusion-processes#6]
Hi, 
thank you for your repository and contributions. 
I am trying to generate a dataset using regression/generate_data.py 
and I encountered an error on line 102.

![image](https://github.com/vdutor/neural-diffusion-processes/assets/88030365/dc67adde-05cd-4d08-bc1a-af59c1f99e7c)

#####################################
  File "/home/coldyoung/neural-diffusion-processes/experiments/regression/generate_data.py", line 30, in <module>
    batch = jitted_get_batch(bkey)
  File "/home/coldyoung/neural-diffusion-processes/experiments/regression/generate_data.py", line 25, in <lambda>
    jitted_get_batch = jax.jit(lambda k: get_batch(k, batch_size=BATCH_SIZE, name=dataset, task=task, input_dim=input_dim))
  File "/home/coldyoung/neural-diffusion-processes/experiments/regression/data.py", line 251, in get_batch
    y = jax.vmap(sample_func)(keys, x)
  File "/home/coldyoung/neural-diffusion-processes/experiments/regression/data.py", line 113, in sample
    f = self.prior.predict(self.params)(x).sample(seed=key, sample_shape=()).reshape(x.shape[0], 1)
  File "/home/coldyoung/anaconda3/envs/dpn/lib/python3.9/site-packages/gpjax/gps.py", line 221, in predict
    mx = self.mean_function(x)
  File "/home/coldyoung/anaconda3/envs/dpn/lib/python3.9/site-packages/gpjax/mean_functions.py", line 151, in __call__
    return jnp.ones((x.shape[0], 1)) * self.constant
AttributeError: 'dict' object has no attribute 'shape'
#####################################
I am unable to determine why this code is using self.params as input in the predict function.

Would you be able to make the necessary changes to the code?
The GPjax library's predict function only accepts array types and not dictionaries.

Could you please resolve this issue?
Thank you.

**Comment by cold-young** [comment]
And I can't find "experiments/regression/eval_gp.py" :30~:34 "neural_diffusion_process.utils".
May I need to use this code? 
When I use the "eval_gp.py" code, 
I got this error that might occur "predict" function. 

#################################################
Traceback (most recent call last):
  File "/home/coldyoung/neural-diffusion-processes/experiments/regression/eval_gp.py", line 107, in <module>
    m = eval_conditional_gp(batch.x_target, batch.y_target, batch.x_context, batch.y_context, batch.mask_context)
  File "/home/coldyoung/neural-diffusion-processes/experiments/regression/eval_gp.py", line 91, in eval_conditional_gp
    post = predict(true_gp.prior, true_gp.params, (x_context, y_context), diag=not fullcov)(x_test)
  File "/home/coldyoung/neural-diffusion-processes/neural_diffusion_processes/gp.py", line 46, in predict
    μx = mean_function(params["mean_function"], x)
TypeError: __call__() takes 2 positional arguments but 3 were given
#################################################

**Comment by vdutor** [comment]
Hi @cold-young ,

Thank you for raising this issue.

GPjax has changed its interface in version `0.6.0`. I have downgraded the dependency to `0.5.9` and the code to generate the data `generate_data.py` and evaluate the gp `eval_gp.py` is working now. You can check the exact version of all my dependencies in this [requirement.txt file](https://github.com/vdutor/neural-diffusion-processes/blob/main/experiments/regression/requirements_Sept2023.txt).

Kind regards,
Vincent

**Comment by vdutor** [comment]
Regarding the `neural_diffusion_process.utils/*` code, I now host this in a standalone package: https://github.com/vdutor/ml-tools/tree/main/ml_tools.

**Comment by cold-young** [comment]
HI, 
Thank you for your answer! 
It's very helpful :+1:  :)
Now I can generate data.

but unfortunately, 
When I train the model from "main.py", 
I may need to use gpjax==0.6.0 because of :20, "from gpjax import linops as jaxlinop"..

maybe we need to two virtual environments for training model and generating data..

**Comment by vdutor** [comment]
That's exactly right. For now, you'll need to switch to another venv to train the model. I apologize for the inconvenience. I will update the data generation code to a new version of gpjax later.

**Comment by cold-young** [comment]
> That's exactly right. For now, you'll need to switch to another venv to train the model. I apologize for the inconvenience. I will update the data generation code to a new version of gpjax later.

Thank you for your kindful comment! :+1:
